# Generated by Django 3.1 on 2020-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='if true=>user has validated OTP correctly in second API'),
        ),
    ]
